version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
  mongodata:
    image: tianon/true
    volumes:
      - ./data:/data/db
    command:
      - echo "Data Container for MongoDb"